[package]
name = "pipeline"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
sherpa-onnx.workspace = true
ct2rs.workspace = true
tracing.workspace = true

[[bin]]
name = "pipe"
path = "src/bin/pipe.rs"

[dev-dependencies]
